# ----------- CONFIGURABLE START -----------
title:            "Marcus' Software Development Blog"
description:      ""
url:              https://nestcx.github.io/scribble # Site url, without a slash at the end.
signoff:          "Marcus" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Home
    url:          /
    external:     false

  - name:         Projects
    url:          /projects
    external:     false

  - name:         Feed
    url:          /feed
    external:     false

  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"



      #create tags here...